### ISSUE TITLE
Restructure files for clarity

### ISSUE THREAD

**Issue by Cristian-Baeza** [s-furlong/Typescript-TicTacToe-Interface#2]
- In prep for (maybe) working on the internal Portal app and for better file readability, we can restructure the project so every component is in its own folder with its corresponding test file: 

![Screen Shot 2022-06-29 at 12 40 01 PM](https://user-images.githubusercontent.com/64428494/176512578-ef3cf17d-1a0e-4bb0-aaeb-5f9b7f748f67.png)

**Comment by s-furlong** [comment]
component and the tests for those components have been moved to their own folders
